services:
  backend:
    build: .
    environment:
      - CHECK_CRON
      - VAPID_PUBLIC_KEY
      - VAPID_PRIVATE_KEY
      - VAPID_SUBJECT
      - CORS_WHITELIST
      - REGISTRATION_DB_PATH=/var/data/registration-db.json
      - PORT=80
    restart: always
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.timetable-push.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.timetable-push.entrypoints=https
      - traefik.http.services.timetable-push.loadbalancer.server.port=80
    volumes:
      - data:/var/data
volumes:
  data:
networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
